project_id = "tpvhkhphufdgfnqofwxf"

[functions.analyze-plan]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.analyze-plan-takeoff]
verify_jwt = true

[functions.ai-material-search]
verify_jwt = true
